### ISSUE TITLE
Error under Big Sur

### ISSUE THREAD

**Issue by hadingtid** [douglas-watson/podcasts_export#1]
I received an error whilst attempting to run this script under Big Sur 11.6.1 (as drag-and-drop feature no longer works since 11.4, this script has regained its relevance). Below is the error message:

Traceback (most recent call last):
File "<stdin>", line 77, in <module>
File "<stdin>", line 50, in main
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/shutil.py", line 415, in copy
copyfile(src, dst, follow_symlinks=follow_symlinks)
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/shutil.py", line 261, in copyfile
with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/User/Music/iTunes/iTunes Media/Podcasts/Zeitsprung – Geschichten aus der Geschichte/ZS72_ Phantominseln.mp3'

Is there any chance this script can be updated to work under Big Sur?

**Comment by douglas-watson** [comment]
I tried to download the same episode, and noticed a few differences: the title now start with GAG and not ZS. Also, your file is located in an iTunes Media folder, whereas mine is located in the Podcasts cache folder. I get the impression this may be an old file dating from iTunes.

I've never used iTunes, so I can't really test my idea on my computer, but here it is: could it be that you downloaded this episode a while ago in iTunes, and somehow this got imported in the Podcasts database? Is there a way you can delete episodes deleted from inside iTunes? Alternatively, can you see that episode listed in Podcasts and delete it from there?

**Comment by itshutrash** [comment]
I also received an error whilst attempting to run this script under Big Sur 11.5.2 
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by hadingtid** [comment]
You're right, those were old itunes files. Opening the database and manually removing all entries stored in locations outside the `/Group Containers/243LU875E5.groups.com.apple.podcasts/` directory fixed the problem described and the script runs fine.

**Comment by douglas-watson** [comment]
> I also received an error whilst attempting to run this script under Big Sur 11.5.2 xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

It sounds like you are missing developer tools. Unfortunately you need to install xcode to be able to execute scripts on macOS. It's easy though: open the Terminal app, paste `xcode-select --install`
 and press Enter. (https://developer.apple.com/forums/thread/673827)



> You're right, those were old itunes files. Opening the database and manually removing all entries stored in locations outside the `/Group Containers/243LU875E5.groups.com.apple.podcasts/` directory fixed the problem described and the script runs fine.

Great! I'll close the issue then.
