### ISSUE TITLE
Include episode date in title

### ISSUE THREAD

**Issue by hadingtid** [douglas-watson/podcasts_export#2]
I'm attempting to move away from using apple's podcast app but I have a rather large backlog of downloaded podcasts which won't retain their chronology when exported. It would be nice to be able to optionally prefix the publishing date to the output filename to preserve this ordering (`~/Export/%Author - %Podcast_title/%Y%m%d %episode_title.mp3`), such as is possible under aggregators like gpodder & similar.

From looking at the database it appears `ZPUBDATE`* is stored as a [Cocoa Core Data timestamp](https://www.epochconverter.com/coredata). I guess it should be possible to convert the cocoa core data timestamp to a human readable date, perhaps via intermediate conversion to a unix timestamp or epoch value. This could then be appended to the `.mp3` title.

In fact, I have tested the idea using a variation on [this script](https://stackoverflow.com/a/39542440) together with individual timestamps from the database, I just don't have enough coding experience to integrate this into your automator script.

Cheers

**Comment by douglas-watson** [comment]
That's a great idea, thanks for finding the database field and the conversion instructions. I uploaded a new version of the workflow that just adds the pubdate in the filename, but I could just as easily change it to create a subfolder per podcast.

**Comment by hadingtid** [comment]
Thanks for integrating that! Actually, subfolders would be great (2000+ files in one folder is a bit unwieldy), it would help to keep the filenames a bit more manageable too.

**Comment by douglas-watson** [comment]
Files are now organised in subfolders, thanks to @neptunix.
